#+title: Encontrarse una película
#+date: 2026-04-04
#+filetags: :ciudad_de_México:Hollywood:cine:

Hace un par de días, salí a la calle y caminé hacia la panadería, una mañana como cualquier otra, para conseguir algo  de desayunar. En estos días de primavera, cuando a la sombra todavía el frescor acicatea el ánimo, antes de que el calor del mediodía convierta el aire en un vapor soporífero y tibio y la gente inunde  las calles del centro de la ciudad, uno puede caminar entre los viejos edificios con cierta ligereza en el cuerpo sabiendo que las excentricidades y fragores típicos de este lugar todavía no terminan de despertar.

Y entonces ahí vi un /set/ de película. En la Avenida 5 de Mayo habían cambiado las fachadas de varias tiendas para imitar negocios de los años 30 o 40 del siglo pasado, con rótulos en inglés, semáforos antiguos y un poste con un letrero que decía "Hollywood Boulevard". Varios figurantes, vestidos con trajes de la época, esperaban indicaciones, algunos charlaban entre sí junto a los autos antiguos, unos doce en total, que ocupaban buena parte de la avenida. El /staff/ de producción se gritaba de un lado a otro de la calle, que no estaba cerrada por completo, y por la que todavía circulaban autos. Una chica encendió un soplador de hojas y lo apuntó hacia una pila de polvo. Una nube espesa y polvorosa cubrió la intersección mientras hombres con radios y chalecos fosforecentes cerraban la calle para despejarla de autos y paseantes. Alguien gritó en un megáfono y de pronto la gente a mi alrededor, un grupo de mirones como yo, atraídos por ese peculiar bullicio, empezó a cuchichear. Varios levantaron el brazo y señalaron con el dedo la figura de un hombre que avanzaba entre la polvareda. Tres o cuatro coches antiguos se pusieron en marcha y pasaron frente a él, los figurantes se movían fingiendo conversaciones o tareas cotidianas. El hombre, de lejos, tenía pinta de pordiosero. Sólo cuando el aire se hubo despejado un poco distinguí una figura extrañamente familiar. Una mujer rubia, vestida como dama de alta sociedad, le arrojó unas monedas, que el hombre recogió con tristeza y resignación antes de seguir su camino.

Cuando los coches antiguos cruzaron la calle y salieron del set, pasando de la ciudad ficticia a la real, un anciano, sucio, vagabundo, de cabellos largos, canosos y grasientos, típico loquito de centro, como les dicen, levantó una ametralladora imaginaria y les disparó mientras hacía ruidos con la boca y sus dentadura intermitente y negruzca se asomaba entre los labios hinchados.

Un hombre vestido con /jeans/ y una gorra de béisbol pasó a escasos metros y le dijo algo a quien parecía ser el primer asistente de dirección, quien comenzó a gritar que todos los actores debían volver a la posición uno para repetir el trazo.

Así vi la misma secuencia repetirse un par de veces, con algunos cambios, hasta que el vacío del estómago se hizo demasiado punzante y decidí volver a casa.

Ahí, tomé mi teléfono y lo confirmé en internet: Todd Haynes estaba filmando una película en la ciudad. Y el protagonista era Pedro Pascal. Salí a comprar un /baguette/ y encontré un pedazo de Hollywood en la calle. Es la clase de cosas que le dan encanto a vivir en el centro de la ciudad de México.

