#+title: La tarde del sábado
#+date: 2026-03-01
#+filetags: :ciudad_de_México:

Mucho tiempo pensé que la ciudad de México era sólo aparentemente
vieja. La mayor parte se construyó en los últimos setenta años. Su
desorden, su ímpetu, sus inconsistencias son la energía de una
aparición imprevista, un chispazo que no ha terminado. Hoy estamos todavía
adentro. La ciudad sigue creciendo, aunque más despacio, y quizá en
estos años nos toque ver el final de esa explosión, cuando la
población irremediablemente envejezca y el vigor expansivo se canse,
mire hacia atrás y se descubra ya sin tanto futuro, en un pasmo, en un
respiro, el primero en mucho rato, que será un vacío raro.

Desde que vivo en el centro, no lejos de la plaza de Santo Domingo,
descubrí otra ciudad, una que sí es vieja de verdad, quizá demasiado
vieja, una que seguramente ha visto peores disminuciones. La caída de
al menos dos imperios, y muchos más gobiernos, y de algún modo ahí
sigue. Y ahora, cuando me descubro pensando en todo lo que pasa en el
tiempo, me consuela ver tanta soledad en cada edificio: de los años
que han pasado, de la distancia que irremediablemente los separa de
quienes los soñaron y alguna vez vivieron en ellos.

Ahí está ya, de una manera que no entiendo, mi sombra, como un
parpadeo eternizado en un instante que yo ya no estaré aquí para ver. 
