#+title:      Un poco de entusiasmo, un poco de expectativa
#+date:       2026-05-17
#+filetags:   :literatura:cuento:lecturas:arte:ficción:

* Una obra maestra del pasado
Acaba de publicarse el último número de /Criticismo/, el cual contiene [[https://criticismo.com/un-destello-de-incertidumbre/][una reseña que escribí]] sobre /Cabeza de Vaca/, la película de Nicolás Echeverría que cuenta la historia de náufrago español, quien, en el siglo XVI, luego de naufragar en las cosas de Florida, emprende un viaje de regreso a la Nueva España, en el que se convierte en una suerte de sacerdote o chamán entre los pueblos indígenas. La película es excepcional y una de las recientes proyecciones en la ciudad de México, a raíz de la publicación de un libro con ilustraciones sobre la película, me hizo revisitarla. La ví hace muchos años, cuando era adolescente. Un profesor de filosofía, entusiasmado por Carlos Castañeda y Antonin Artaud, la proyectó a sus alumnos. La vimos en una pequeña computadora, con bocinas que se escuchaban mal. La impresión que me dejó fue, sin embargo, mayor. Es una de esas grandes películas de las que se habla poco o, me lo parece, no lo suficiente. Ya no se hacen películas así. Pertenece, quizá, a otra época, y a otro tipo de ambiciones. Pero todavía es una película particularmente reveladora sobre muchos temas y aspectos de la Conquista y de la relación que tenemos con ese evento y con el mundo prehispánico. Echevarría es un cineasta que hizo pocas películas, cuyos temas, además se perciben demasiado locales o antropológicos para ver en ellos la mano de un artista antes que la de un mero registrador de realidades ya en sí mismas bastante interesantes. /Cabeza de Vaca/ demostró justo lo opuesto, y en su particularidad y aislamiento, pues no hay todavía muchas películas que cubran con profundidad sus temas, perdura como una de las miradas más abiertamente modernas al problema que fue y sigue siendo la llegada de los europeos a América.

* ¿Una obra maestra del presente?
De un tiempo para acá, me hice asiduo de los pódcasts. Los escuchó mientras camino al trabajo, limpio la casa o lavo los trastes. La mayoría de los que me interesan tratan sobre asuntos de actualidad y son en inglés. La excepción es /[[https://archivogeneral.simplecast.com/][Archivo general]]/, un podcast sobre literatura y la historia intelectual de México que alguien me recomendó hace tiempo. Es el único pódcast que he encontrado que trata exclusivamente sobre la literatura y la historia de México, y es estimulante que sus conductores que hablen de literatura teniendo un horizonte de ideas sobre la historia y la cultura.

En su última emisión, elogian ampliamente un libro de cuentos publicado el año pasado, /Siempre un lugar efímero/, de Luis Madrigal, al que consideran una obra maestra contemporánea, igual de buena que los mejores libros de cuentos de la historia. 

Como con cualquier declaración excesiva de entusiasmo hacia una obra de arte, la recomendación despertó en mí algo de escepticismo, curiosidad y esperanza combinadas. En mi experiencia, es raro que una manifestación de fervor, especialmente cuando proviene de una publicación o de un medio audiovisual, esté a la altura de sus afirmaciones cuando se trata del presente. La única recomendación de novedades que me soprendió profundamente fue /Vivir abajo/, novela para mí desconocida, de un autor desconocido también, de la que un amigo me habló con gran entusiasmo y que ha sido una de las lecturas más apasionantes que recuerdo de los últimos años. Se trata, sin embargo, de una doble excepción: pocos elogios de obras contemporáneas se atreven a elevarlas a lo mejor de la historia, y cuando lo hacen casi nunca  me entusiasman a ese mismo grado.

Por eso recibí la recomendación de /Siempre un lugar efímero/ con reservas. El libro se consigue en Amazon, y no en otro lugar, tristemente. Es breve y lo leí en un par de días.

A medida que avanzaba por las páginas, no podía dejar de pensar en qué tanto mi lectura estaba determinada por las aseveraciones de su grandeza y calidad. Sentía que lo leía como midéndolo para determinar si era tan bueno como lo decían. Cierto humor, la buena prosa y situaciones peculiares me sumergían en los cuentos pero nunca perdí del todo la sensación de que el ruido de fondo de la expectativa me distrajo.

Al final, creo que entiendo el entusiasmo, aunque no lo comparto, y mucho menos podría decir que se trata de uno de los mejores libros de cuento de la historia, no sólo porque es un género que no conozco muy bien y del que leído proporcionalmente poco, sino porque hay en él mucho que no disfruté. Los personajes históricos, Winston Churchill, Joseph Smith, Leonard Cohen, Moctezuma, aparecen y desaparecen como anécdotas interesantes, pero un tanto acartonadas, míticas, en cierta manera, pero de un mito con el que el humor del libro, que es lo mejor, no sabe muy bien qué hacer. El final del último cuento, que hasta ese momento me parecía sin duda lo mejor de la colección, me decepcionó. Hay una ironía que a veces se abandona para asumir tonos más serios en el momento preciso, como en el primer cuento, y a veces se convierte en un chiste apagado, sin mayor resonancia, como en el último cuento.

No pocas veces me reí. La novela del escritor guatemalteco del primer cuento es ridícula y conmovedora a la vez. Hay patetismo en su figura y cierta sorna que no está excenta de comprensión o simpatía. En su derrota y su humillación hay algo muy humano. La visión del artista como un  ser entre misterioso y patético se concreta mejor aquí que con el cuento que tiene como protagonista a Julián, cuya obra consiste en hacer grietas en edificios y cavar un agujero. La voluntad especulativa de imaginar una obra de arte que es puro evento y pura belleza, casi como un milagro, tiene algo de poético pero su inverso, en la ridícula y necia figura del padre que envidia al hijo, es un tono menor demasiado mezquino para hacer del verdadero artista algo más que la idea del genio, frente a cuyo hermetismo y evocación todo lo demás parece insignificante.

La peculiaridad de ciertas situaciones, como el viaje en autobús con un grupo de turistas chinos, el incidente del tenedor, las protestas contra la injusticia en Los Ángeles o la pasión por el mundo azteca que asalta al suburbanita estadounidense al final son retratos finos de cierto humor desapegado, ligero, inteligente, quizá un poco superficial y ocurrente, pero no por eso menos simpático y, por momentos, inesperado. Los personajes viven en mundos medio irreales, medio desarraigados, que pasan fácilmente de un escenario a otro y que, más que vividos, son imaginados, la densidad de su experiencia es poca y la evocación de su circunstancia es mucha. No son personas de carne y hueso, son impresiones, deseos, imágenes que se extienden más allá de la imrpresión momentánea y, a veces, llegan a lugares interesantes.

Hace poco apareció [[https://www.nexos.com.mx/el-descontento-del-realismo/][un ensayo]] /Nexos/ que defendía una tesis interesante. Leyendo este libro recordé una de sus frases sobre, si no mal recuerdo, un libro de Yuri Herrera: "Le interesa la verdad de la lectura, no de la escritura". No sé si la ambición de /Siempre un lugar efímero/ sea ir contra del realismo mimético en la literatura, al menos no de manera consciente, pero sin duda pertenece a esa estirpe bolañesca para la cual el arte y la realidad se confunden porque la vida es arte y viceversa. O porque lo más interesante de la vida parece ser el arte: cuando los personajes son artistas, y también cuando el arte acosa a la vida, como en el cuento del viaje a Ixtapa, o cuando la fábrica misma de la realidad, la historia con mayúsculas, se interviene con ánimo creativo, como en el último cuento. No seré yo quien niegue que la vida es arte y representación, y que da lo mismo la relación de una obra o su autor con la "realidad" cuando la lectura satisface por sí misma, pero también echo en falta en este ánimo la intimidad entre el arte y la vida que, sin confundirlas, las ilumina mutuamente. Algo de eso percibí en el cuento del escritor guatemalteco, por ejemplo.

¿Cuál es la verdad de la vida sin el arte? Tal vez ninguna, pero también creo que el arte sin la vida, sin esa parte de la vida que no se siente como arte, que no es lo que imaginamos sino lo que vivimos, es poco más que un adorno, un embellecimiento inane, un bello espejismo.

No digo que eso sea el libro de Madrigal, que tiene más virtudes que defectos, y que en momentos deja brillar, como las grietas de ese artista imaginario, la luz de una inspiración genuina y un ingenio hábil, y en ello encuentro suficientes razones para el entusiasmo.

Quizá si vuelva a leerlo, habiendo pasado ya el bullicio de la expectativa, otra será mi opinión. 



